version: '3.7'
services:
 
 # container netdata
 netdata:
  image: netdata/netdata
  container_name: netdata  
  hostname: localhost
  ports:
   - 19999:19999
  cap_add:
   - SYS_PTRACE
  security_opt:
   - apparmor:unconfined
  volumes:
   - /proc:/host/proc:ro
   - /sys:/host/sys:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
 
 # container grafana
 grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
   - 3000:3000
  environment:
   GF_SECURITY_ADMIN_PASSWORD: grafana
  restart: always
 
 # container prometheus
 prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  links:
   - netdata
  command:
   - '--config.file=/etc/prometheus/prometheus.yml'
  volumes:
   - pwd_result/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # put the result of the pwd command instead of pwd_result
  ports:
   - 9090:9090